SHELL := /bin/bash

.PHONY: help
help: ## This help message
	@echo -e "$$(grep -hE '^\S+:.*##' $(MAKEFILE_LIST) | sed -e 's/:.*##\s*/:/' -e 's/^\(.\+\):\(.*\)/\\x1b[36m\1\\x1b[m:\2/' | column -c2 -t -s :)"

.PHONY: clean-img
clean-img: ## Remove autogenerated image files
	rm -rf public/
	find static -name "*.avif" -delete
	find static -name "*.webp" -delete

.PHONY: clean-pub
clean-pub: ## Remove build files
	rm -rf public/
	rm -f static/tinysearch_engine*

.PHONY: clean
clean: clean-pub clean-img ## Remove public files and images

.PHONY: versions
versions: ## Show versions of tools
	@echo "=== Checking installed tools ==="
	@if command -v zola >/dev/null 2>&1; then echo "✅ zola: $$(zola --version)"; else echo "⚠️ zola: not installed"; fi
	@if command -v gh-stats >/dev/null 2>&1; then echo "✅ gh-stats: $$(gh-stats --version 2>&1 | head -1)"; else echo "⚠️ gh-stats: not installed (optional)"; fi
	@if command -v tinysearch >/dev/null 2>&1; then echo "✅ tinysearch: $$(tinysearch --version 2>&1 | head -1)"; else echo "⚠️ tinysearch: not installed (optional)"; fi
	@if command -v wasm-opt >/dev/null 2>&1; then echo "✅ wasm-opt: $$(wasm-opt --version 2>&1 | head -1)"; else echo "⚠️ wasm-opt: not installed (optional)"; fi
	@if command -v terser >/dev/null 2>&1; then echo "✅ terser: $$(terser --version 2>&1 | head -1)"; else echo "⚠️ terser: not installed (optional)"; fi
	@if command -v cavif >/dev/null 2>&1; then echo "✅ cavif: $$(cavif --version 2>&1 | head -1)"; else echo "⚠️ cavif: not installed (optional)"; fi
	@if command -v convert >/dev/null 2>&1; then echo "✅ ImageMagick: $$(convert -version 2>&1 | head -1)"; else echo "⚠️ ImageMagick: not installed"; fi

.PHONY: content
content: ## Build the content of the static site with zola
	zola build

.PHONY: images
images: ## Create avif images
	@if command -v cargo >/dev/null 2>&1; then \
		cargo run --manifest-path ./helpers/img/Cargo.toml; \
	else \
		echo "⚠️  cargo not installed, skipping image generation"; \
	fi

# Creating a temporary directory here because wasm-pack seems to overwrite
# the public output directory. Haven't yet found the reason why.
.PHONY: index
index: content ## Build the search index with tinysearch
	@if command -v tinysearch >/dev/null 2>&1; then \
		mkdir -p tinysearch_out && \
		RUST_LOG=debug tinysearch --release --optimize --path tinysearch_out public/tinysearch.json/index.html && \
		mv tinysearch_out/* public && \
		rm -rf tinysearch_out; \
	else \
		echo "⚠️  tinysearch not installed, skipping search index"; \
	fi

.PHONY: minify
minify: ## Compress JavaScript assets
	@if command -v terser >/dev/null 2>&1; then \
		terser --compress --mangle --output public/search_min.js -- static/search.mjs; \
	else \
		echo "⚠️  terser not installed, skipping minification"; \
	fi

.PHONY: build build-ci
build: stars content index minify ## Build static site and search index, minify JS (full build)
build-ci: content index minify ## Build static site without stars (CI-only, no API token required)

.PHONY: build-quick
build-quick: stars content ## Build static site (includes star stats)

.PHONY: dev run serve
dev run serve: ## Serve website locally
	zola serve --fast

.PHONY: stars
stars: ## Update Github stars statistics for my projects
	@if command -v gh-stats >/dev/null 2>&1 && [ -n "$$GITHUB_TOKEN" ]; then \
		rm -f content/static/about/stars.md; \
		gh-stats --filter gitpod --stars 100 --template .star-counter-template.md --output content/static/about/stars.md 2>/dev/null || echo "⚠️  gh-stats failed, using fallback content"; \
	elif command -v gh-stats >/dev/null 2>&1 && [ -z "$$GITHUB_TOKEN" ]; then \
		echo "⚠️  gh-stats available but GITHUB_TOKEN not set, skipping statistics"; \
		python3 -c "import sys; content = '---\ntitle: \"GitHub Star Statistics\"\ndate: 2020-01-01\n---\n\n# GitHub Star Statistics\n\n暂无可用的星标统计数据。\n\n该功能需要有效 GitHub token 才能从 API 获取实时数据。\n'; f = open('content/static/about/stars.md', 'w', encoding='utf-8'); f.write(content); f.close()"; \
	else \
		echo "⚠️  gh-stats not installed, skipping star statistics"; \
		python3 -c "import sys; content = '---\ntitle: \"GitHub Star Statistics\"\ndate: 2020-01-01\n---\n\n# GitHub Star Statistics\n\n暂无可用的星标统计数据。\n\n该功能需要 gh-stats 工具才能从 GitHub API 获取实时数据。\n\n## 状态\n\n- **本地开发**：此功能已配置为可选跳过\n- **CI/CD 构建**：使用 GitHub Actions 安装所需工具\n- **产品环境**：依赖 Cloudflare 秘钥配置\n\n功能正常运行，不影响主内容构建和部署。\n'; f = open('content/static/about/stars.md', 'w', encoding='utf-8'); f.write(content); f.close()"; \
	fi
